### ISSUE TITLE
Automatically generated hyperlinks might have * in them

### ISSUE THREAD

**Issue by amstan** [markdown-it/markdown-it#749] opened 2021-01-05 06:36 UTC
Links such as: https://www.wolframalpha.com/input/?i=%283840+*+2160%29+%2F+%28640+*+480%29 have `*` in them, but markdown-it seems to prefer evaluating the * before the link parsing. This yields with a pretty broken link:
> <https://www.wolframalpha.com/input/?i=(3840+>+2160%29+%2F+%28640++480%29

I've noticed this while using https://github.com/vector-im/element-web.

Note github's rendering works just fine (first link in this bug report).

[Reproduced in https://markdown-it.github.io/ ](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22https%3A%2F%2Fwww.wolframalpha.com%2Finput%2F%3Fi%3D%25283840%2B%2A%2B2160%2529%2B%252F%2B%2528640%2B%2A%2B480%2529%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)

In terms of the spec, seems like bare links are not really specified, [closest thing I found an address surrounded by `<  >`](https://spec.commonmark.org/0.29/#autolinks). But still, I would think that it should be expected that these work.

[Attempting to reproduce in: https://spec.commonmark.org/dingus](https://spec.commonmark.org/dingus/?text=https%3A%2F%2Fwww.wolframalpha.com%2Finput%2F%3Fi%3D%25283840%2B*%2B2160%2529%2B%252F%2B%2528640%2B*%2B480%2529%0A%0A%3Chttps%3A%2F%2Fwww.wolframalpha.com%2Finput%2F%3Fi%3D%25283840%2B*%2B2160%2529%2B%252F%2B%2528640%2B*%2B480%2529%3E%0A%0A%0A%0A)

**Comment by puzrin** [comment] 2021-01-06 11:35
Seems dupe of https://github.com/markdown-it/markdown-it/issues/38

**Comment by amstan** [comment] 2021-01-06 22:40
It seems so. But I am a little disappointed that #39 was closed because there's a workaround. I wouldn't call `<>` good enough.

Naked http links are trying to be supported in markdown-it, despite the spec not caring about them (as far as i know). They either should work properly without such corner cases (like github's parser does) or if we want 100% spec compliance not support them at all.

In terms of [element's](https://github.com/vector-im/element-web) need for this formatting: Element is essentially a chat app. it would be weird to ask friends to use <> for any link they send me just in case there's weird special characters in there. It would equally be weird if naked http links are not converted to links.

**Comment by puzrin** [comment] 2021-01-06 22:55
You can disable autolinker or even force strict commonmark mode via presets if needed.

Pevious issue was closed because no plans to spend signifiant time for autolinker rewrite. But anyone can suggest PR. I explained details somewhere before.

closing as dupe.

**Closed by puzrin** 2021-01-06 22:55 UTC
