### ISSUE TITLE
strikethrough incorrect for 3+ tildes

### ISSUE THREAD

**Issue by dwelle** [markdown-it/markdown-it#301] opened 2016-11-22 12:15 UTC
```
~~~text~~~
```

renders to (taken from markdown-it's repl):

```
<pre class="hljs"><code></code></pre>
```

GFM ignores the extra `~` and renders:

```
<p><del>text</del></p>
```

**Comment by puzrin** [comment] 2016-11-23 02:52
See [example](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22foo%20~~~text~~~%5Cn%5Cn~~~text~~~%5Cn%5Cn%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D). `~~~` at start of line is a fenced block, according to CM spec.

I'd recommend to discuss at commonmark forum https://talk.commonmark.org/t/a-problem-with-backtick-code-fences/1053

**Comment by puzrin** [comment] 2016-11-23 02:58
Do you have example from real world when `~~~` needed at start of paragraph?

**Comment by dwelle** [comment] 2016-11-23 11:38
E.g. when users mistype and wonder why their text suddenly disappeared.

**Comment by puzrin** [comment] 2016-11-23 14:18
spec.commonmark.org/0.27/#fenced-code-blocks it's better to discuss spec-related things in other place.

closing as not a bug.

**Comment by dwelle** [comment] 2016-11-23 16:41
Still, as I said above, acc to CM spec, the closing `~~~` must not be on the same line as the opening sequence, else it's not considered a code block.

Any text after opening fenced block sequence is considered `info` string, and if the line contains the closing sequence, it's not considered code block at all.

The spec is kinda not explicit about this, tho, but it can be verified at their dingus.

input:

```
~~~text~~~
```

CM output:
```
<p>~~~text~~~</p>
```
md-it output:

```
<pre class="hljs"><code></code></pre>
```

So currently, md-it is not spec compliant.

**Closed** 2016-11-30 13:20 UTC
Labels: cm spec, question
