### ISSUE TITLE
Undefined variable used in smartquotes.js line 29...

### ISSUE THREAD

**Issue by digitalmoksha** [markdown-it/markdown-it#76] opened 2015-03-24 16:44 UTC
Not a big deal, but currently at line 29 of smartquotes.js you're testing against an undefined variable, `token.text`

`    if (token.type !== 'text' || QUOTE_TEST_RE.test(token.text)) { continue; }`

I think the test against QUOTE_TEST_RE will always be false, and changing to `token.content` seems to cause breakage.  Anyway, just wanted to bring to your attention.

**Comment by puzrin** [comment] 2015-03-24 21:58
/cc @rlidwka 

Alex, take a look please. Is is a garbage from old algorythm or we still can make a quick path in other way for check?

**Comment by rlidwka** [comment] 2015-03-25 14:56
This check was for performance reasons, we decided to remove it since it doesn't actually improve anything. Fixed in https://github.com/markdown-it/markdown-it/commit/e91574c391a4e86dfbcfbe3aa8250e7468fec0e1 .

-----

And just for the fun of it, about that undefined variable thing. We had three bugs cancelling each other out:
    
   1. `token.text` should be `token.content`. We never had `token.text` here, so it must've been a typo.
    
   2. `.test()` condition should be negated, because we need to skip tokens without quotes, not with them.
    
   3. the entire `if` statement is in the wrong place messing with level calculations

So the clean fix (so that it would work as intended afterwards) would look like this:

```diff
diff --git a/lib/rules_core/smartquotes.js b/lib/rules_core/smartquotes.js
index 948f595..cfa3349 100644
--- a/lib/rules_core/smartquotes.js
+++ b/lib/rules_core/smartquotes.js
@@ -26,8 +26,6 @@ function process_inlines(tokens, state) {
   for (i = 0; i < tokens.length; i++) {
     token = tokens[i];
 
-    if (token.type !== 'text' || QUOTE_TEST_RE.test(token.text)) { continue; }
-
     thisLevel = tokens[i].level;
 
     for (j = stack.length - 1; j >= 0; j--) {
@@ -35,6 +33,8 @@ function process_inlines(tokens, state) {
     }
     stack.length = j + 1;
 
+    if (token.type !== 'text' || !QUOTE_TEST_RE.test(token.content)) { continue; }
+
     text = token.content;
     pos = 0;
     max = text.length;
```

**Closed** 2015-03-25 18:17 UTC

**Comment by digitalmoksha** [comment] 2015-03-26 08:19
Cool, thanks for looking into it...

**Comment by digitalmoksha** [comment] 2015-03-27 13:20
@puzrin @rlidwka 

btw, just wanted to let you guys know that I ported markdown-it to Ruby and RubyMotion and have released it as a gem today (https://github.com/digitalmoksha/motion-markdown-it) - that's why I even ran across the above bug.  There are still some tests that need passing and various other tweaks, but it's working pretty well so far.  This allows it to be used in a Rails backend or RubyMotion app.

Appreciate the work done you guys have done on markdown-it.

Cheers

**Comment by puzrin** [comment] 2015-03-27 13:31
Wow, you a real hero if you could understand every line of this madness :) !

I've added link to readme, and recommend to post your acheivement to http://talk.commonmark.org/c/implementation

**Comment by digitalmoksha** [comment] 2015-03-27 14:03
I can't really say I understand every piece yet :)

Thanks for the link in the readme.  And yeah, I guess I should post to the CM forum...
