### ISSUE TITLE
Glitches when putting code block inside quote

### ISSUE THREAD

**Issue by arximboldi** [markdown-it/markdown-it#119] opened 2015-06-08 23:58 UTC
Hi!

When putting a code block inside a quote using this syntax:

```
> ```
> some code
> ```
```

An extraneous `>` symbol is added at the end of the block. You can see an example of this erratic behaviour here [0]. However Docco and Github render that correctly. Also, after playing with the `markdown-it` playground [1], it seems to handle that syntax correctly if and only if the code block contains more than one line.

Thanks a lot!

[0] https://www.npmjs.com/package/mixco
[1] https://markdown-it.github.io/

**Comment by puzrin** [comment] 2015-06-09 00:03
Did you tried version from master? That seems a dupe of #116

Release will be in 1-2 days, need to finish minor things.

**Comment by puzrin** [comment] 2015-06-09 00:06
version in master seems to work right

**Comment by arximboldi** [comment] 2015-06-09 07:18
Oh, sorry for dupe, didn't find the other one. Thanks a lot!

**Closed** 2015-06-12 17:44 UTC
