### ISSUE TITLE
[plugin:vite:vue] Element is missing end tag.

### ISSUE THREAD

**Issue by xingkongdiyiren** [markdown-it/markdown-it#933] opened 2023-06-01 01:52 UTC
36 |  class Notepad<K,V>{     
37 |      private K key ;  
38 |      private V value ; 
   |           ^
39 |      public K getKey(){  
40 |          return this.key ;
    at createCompilerError (D:\vscodeproject\myblog\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:18:17)
    at emitError (D:\vscodeproject\myblog\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:1487:5)
    at parseElement (D:\vscodeproject\myblog\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:1031:5)
    at parseChildren (D:\vscodeproject\myblog\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:844:18)
    at parseElement (D:\vscodeproject\myblog\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:1008:20)
    at parseChildren (D:\vscodeproject\myblog\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:844:18)
    at parseElement (D:\vscodeproject\myblog\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:1008:20)
    at parseChildren (D:\vscodeproject\myblog\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:844:18)
    at parseElement (D:\vscodeproject\myblog\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:1008:20)
    at parseChildren (D:\vscodeproject\myblog\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:844:18
Click outside or fix the code to dismiss.
You can also disable this overlay by setting server.hmr.overlay to false in vite.config.js.

Question: 1, why would he scan the code in my code block, shouldn't he filter himself, I use markdown syntax, specifically for ```java```

2, I also found a very strange problem, why he does not support the external link to visit, is my picture is not local, is the website he can not visit

3, if you have a good solution, please give me a solution, thank you

**Comment by rlidwka** [comment] 2023-06-01 03:05
what does it have to do with markdown-it?

https://github.com/vuejs/vitepress/issues/2460

**Comment by brc-dd** [comment] 2023-08-25 18:22
Hey Alex, feel free to close this here as well. I believe the issue is OP has some typo in markdown syntax and VitePress' Vue compiler is throwing error as `<K,V>` has no closing tag.

**Closed** 2023-08-25 18:44 UTC
