### ISSUE TITLE
`abc~~,a~~` not rendered to `abc <s>,a</s>`

### ISSUE THREAD

**Issue by scil** [markdown-it/markdown-it#199] opened 2016-02-08 15:14 UTC
https://markdown-it.github.io/#md3={%22source%22%3A%22abc~~%2Ca~~\n\n%23%23%20ok\n~~.a~~%20\n\n~~%2Ca~~%20\n\na%20~~.a~~%20\n\na%20~~%2Ca~~%20\n\na%20~~%E3%80%82a~~%20\n\n%23%23%20not%20work\n\na~~.a~~\n%20\na~~%2Ca~~%20\n\na~~%E3%80%82a~~%20\n%22%2C%22defaults%22%3A{%22html%22%3Atrue%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22}}

**Comment by rlidwka** [comment] 2016-02-09 09:57
There is no specification for strikeout tag, so we decided to implement it exactly like strong emphasis in CommonMark. If you replace `~~` with `**` and check [there](http://spec.commonmark.org/dingus/), it should be parsed the same way.

So according to that, `~~` preceded by an alphanumeric and followed by punctuation cannot open `<s>` tag, it can only close it. The reason being that `~~(~~foo~~)~~` should be rendered as `<s>(<s>foo</s>)</s>`, not `<s>(</s>foo<s>)</s>`.

Not a bug. It is different from github implementation, but I hope they will fix it soon. :)

**Closed by rlidwka** 2016-02-09 09:57 UTC

**Comment by scil** [comment] 2016-02-29 07:36
I would say " implement it exactly like strong emphasis"  not better for  <s>.

Because any text partials including punctuations maybe deleted.  And only some words may need strong emphasis.

**Comment by rlidwka** [comment] 2016-03-28 08:10
> Because any text partials including punctuations maybe deleted. And only some words may need strong emphasis.

If you want to strike out punctuation, just add a space. This would work:

```md
~~(~~ foo ~~)~~
```

Yes, it is somehow limiting. But I feel it's still better than having separate rules for strikeout and emphasis.
