### ISSUE TITLE
is their any option to convert HTML into MD format?

### ISSUE THREAD

**Issue by sunilattosol** [markdown-it/markdown-it#667] opened 2020-05-14 13:02 UTC
I have html 
```html
<blockquote>
<blockquote>
<p>Blockquotes can also be nested. Hello <strong>World</strong></p>
</blockquote>
</blockquote>
```
and I want to convert these html code into markdown like below
```md
> > Blockquotes can also be nested. Hello **World**
```

**Comment by puzrin** [comment] 2020-05-14 13:22
Dupe of #666. Please, don't create issues not related to this repo.

**Closed by puzrin** 2020-05-14 13:22 UTC
