### ISSUE TITLE
Certain tables under bullet points are not rendered

### ISSUE THREAD

**Issue by c3er** [markdown-it/markdown-it#1022] opened 2024-04-16 19:48 UTC
The third table in [this demo](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%7C%20T1%20%20%20%7C%20T2%20%20%20%7C%5Cn%7C%20----%20%7C%20----%20%7C%5Cn%7C%20C1R1%20%7C%20C2R2%20%7C%5Cn%7C%20C1R2%20%7C%20C2R2%20%7C%5Cn%5Cn-%20Under%20a%20bullet%20point%5Cn%20%20%7C%20T1%20%20%20%7C%20T2%20%20%20%7C%5Cn%20%20%7C%20----%20%7C%20----%20%7C%5Cn%20%20%7C%20C1R1%20%7C%20C2R2%20%7C%5Cn%20%20%7C%20C1R2%20%7C%20C2R2%20%7C%5Cn%5Cn-%20Under%20a%20bullet%20point%20but%20shifted%20to%20the%20left%5Cn%20%7C%20T1%20%20%20%7C%20T2%20%20%20%7C%5Cn%20%7C%20----%20%7C%20----%20%7C%5Cn%20%7C%20C1R1%20%7C%20C2R2%20%7C%5Cn%20%7C%20C1R2%20%7C%20C2R2%20%7C%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Afalse%2C%22typographer%22%3Afalse%2C%22_highlight%22%3Afalse%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D) is not rendered. It is not indented "correctly" to belong to the bullet point, but I still expect, that a table appears, however positioned.

![Screenshot of three table attempts, the third doesn't render](https://github.com/markdown-it/markdown-it/assets/24460532/6fc47538-f0bb-421a-a3d7-97eeca935ddd)

**Comment by rlidwka** [comment] 2024-04-16 23:13
Github doesn't render this either:

- Under a bullet point
  | T1   | T2   |
  | ---- | ---- |
  | C1R1 | C2R2 |
  | C1R2 | C2R2 |

- Under a bullet point but shifted to the left
 | T1   | T2   |
 | ---- | ---- |
 | C1R1 | C2R2 |
 | C1R2 | C2R2 |

There's gotta be a good reason for it, but I can't come up with one from the top of my head.

**Comment by ElektroStudios** [comment] 2024-04-17 00:32
> Github doesn't render this either:
>
> There's gotta be a good reason for it, but I can't come up with one from the top of my head.

Nothing is perfect, we should not consider GitHub's parsing logic to be bug-free, then maybe the reason could be simply a lack of reported cases to be aware of the syntax problem and thus give support to fix it.

Or maybe I'm wrong, and you're right, but if no body can't come up with a good reason for it... I think that makes my conclusion more likely.

Just saying!, perfection shouldn't be taken for granted.

**Comment by puzrin** [comment] 2024-04-17 10:19
In this project scope, we do not discuss spec-related things "how markdown should be rendered". That's an independent, and very complicated process. We just follow CM spec, and missed parts follow github's behavior (except more advanced auto-linking).

Of course, people can have different opinions, but if you don't like existing mainstream behavior about tables, I see 2 ways:

- Write a request to github guys about spec update.
- Create a custom plugin.

IMHO, if current behavior does not diverge from github, we should not change anything here.

Closing as "not a bug". But feel free to add more clarifications if you like to share something important.

**Closed by puzrin** 2024-04-17 10:19 UTC

**Comment by c3er** [comment] 2024-04-17 16:39
> Write a request to github guys about spec update.

[Done](https://github.com/orgs/community/discussions/119981)

Do I understand you right, @puzrin that GitHub's Markdown rendering behavior is basically treated as holy, how much certain corner cases look like actual bugs?

BTW: Tables shifted to the right of the last bullet point are rendered by Markdown and this project. So, I cannot imagine any reason, except implementation error, for this behavior.

---

```
- Under a bullet point but shifted to the right
   | T1   | T2   |
   | ---- | ---- |
   | C1R1 | C2R2 |
   | C1R2 | C2R2 |
```

- Under a bullet point but shifted to the right
   | T1   | T2   |
   | ---- | ---- |
   | C1R1 | C2R2 |
   | C1R2 | C2R2 |

**Comment by puzrin** [comment] 2024-04-17 17:01
IMHO I said explicitly - we follow CM spec and Github spec to not create "yet another markdown render behavior". So, if anyone wishes to report the bug here - it is expected to be a deviation from above. The rest is out of scope.

As alternative - the package has flexible architecture. Anyone can create a plugin with custom behavior.

**Comment by rlidwka** [comment] 2024-04-17 18:11
> Do I understand you right, @puzrin that GitHub's Markdown rendering behavior is basically treated as holy

*yes, thou shalt worship thy microsoft overlords, for they can do no wrong*

> BTW: Tables shifted to the right of the last bullet point are rendered by Markdown and this project. 

Tables shifted to the **right** by 1-3 spaces are considered a normal markdown text inside the list.

Tables shifted to the **left** are a paragraph continuation instead (if it's anything else than a text, it'll be placed outside of the list as per spec).

You can also see a difference in behavior between those two:

```md
- hello
 world
 -----

- hello
   world
   -----
```

For completeness' sake, worth mentioning that blockquotes work similarly: 

```md
> Here's a table:
> | T1   | T2   |
> | ---- | ---- |
> | C1R1 | C2R2 |
> | C1R2 | C2R2 |

> And here's not:
| T1   | T2   |
| ---- | ---- |
| C1R1 | C2R2 |
| C1R2 | C2R2 |
```

> So, I cannot imagine any reason, except implementation error, for this behavior.

That is perhaps due to a lack of imagination.

There's one very good reason for it, which is compatibility with other parsers. And that's good enough for me to be honest.

**Comment by c3er** [comment] 2024-04-17 20:00
> There's one very good reason for it, which is compatibility with other parsers. And that's good enough for me to be honest.
>
> **edit:** to clarify, there are reasons to do it this way, there are reasons to do it the other way. And all things being equal, same behavior as other parsers is a very good argument to keep things as is.

Staying "compatible" to GitHub is already a weak argument IMO but this is actually invalid. While Remarkable behaves the same as markdown-it and GitHub, other parsers behave differently. Marked renders even all cases as one would expect naively!

Also, I think on the whole platform are like two people at most who intentionally produced such a string that shall not render as a table.

![Screenshot of different Markdown parsers side by side](https://github.com/markdown-it/markdown-it/assets/24460532/9dc6b8c4-07f8-42d2-afa5-7dc57bcb1c92)
