### ISSUE TITLE
Non-spaced indented entirely automatically numbered lists do not render, and spaced lists do not render correct subsequent line spacing.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [markdown-it/markdown-it#939] opened 2023-06-09 22:55 UTC
Summarily, nested non-spaced automatically numbered (0.) lists don't render more than one level deep without indentation, whereas manually numbered lists do, and spaced lists do not render correctly.

More specifically, per https://github.com/microsoft/vscode/issues/184429#issue-1744161712:

<blockquote>

@mjbvz,

> Commonmark also won't render this correctly at all without a new line before the nested list: [commonmark demo](https://spec.commonmark.org/dingus/?text=0.%09test%0A0.%09test%0A%090.%09test%0A%090.%09test)

It wouldn't make sense that

```markdown
0.	Placeholder
	1.	Placeholder
	2.	Placeholder
	3.	Placeholder
	4.	Placeholder
0.	Placeholder
	1.	Placeholder
0.	Placeholder
```

is rendered correctly then, when

```markdown
0.	Placeholder
	0.	Placeholder
	0.	Placeholder
	0.	Placeholder
	0.	Placeholder
0.	Placeholder
	0.	Placeholder
0.	Placeholder
```

is not:

![image](https://github.com/microsoft/vscode/assets/42837531/4aec474f-a9ce-40ce-9a78-205e16bafce5)

---

However, the spaced indented lists don't render correctly either:

```markdown
0.	**Manually numbered indented section**

	0.	**Non-separated**

		0.	Placeholder
			1.	Placeholder
			2.	Placeholder
			3.	Placeholder
			4.	Placeholder
		0.	Placeholder
			1.	Placeholder
		0.	Placeholder

	0.	**Separated**

		0.	Placeholder

			1.	Placeholder
			2.	Placeholder
			3.	Placeholder
			4.	Placeholder

		0.	Placeholder

			1.	Placeholder

		0.	Placeholder

0.	**Manually numbered indented section**

	0.	**Non-separated**

		0.	Placeholder
			0.	Placeholder
			0.	Placeholder
			0.	Placeholder
			0.	Placeholder
		0.	Placeholder
			0.	Placeholder
		0.	Placeholder

	0.	**Separated**

		0.	Placeholder

			0.	Placeholder
			0.	Placeholder
			0.	Placeholder
			0.	Placeholder

		0.	Placeholder

			0.	Placeholder

		0.	Placeholder
```

is rendered as

![image](https://github.com/microsoft/vscode/assets/42837531/cf35a6f6-9b56-42a9-8360-a0995c7a0906)

</blockquote>

**Comment by rlidwka** [comment] 2023-06-10 11:59
Working as intended, and I'm quoting the CommonMark spec below (see https://spec.commonmark.org/0.30/#lists):

> In order to solve the problem of unwanted lists in paragraphs with
> hard-wrapped numerals, we allow only lists starting with `1` to
> interrupt paragraphs.  Thus,
> 
> ```````````````````````````````` example
> The number of windows in my house is
> 14.  The number of doors is 6.
> .
> <p>The number of windows in my house is
> 14.  The number of doors is 6.</p>
> ````````````````````````````````
> 
> We may still get an unintended result in cases like
>
> ```````````````````````````````` example
> The number of windows in my house is
> 1.  The number of doors is 6.
> .
> <p>The number of windows in my house is</p>
> <ol>
> <li>The number of doors is 6.</li>
> </ol>
> ````````````````````````````````
> 
> but this rule should prevent most spurious list captures.

We can't fix this, because changing edge case like this is less important than compatibility with all other commonmark parsers.

If you want, you can raise this issue again in their forum (https://talk.commonmark.org) or spec repo (https://github.com/commonmark/commonmark-spec). But it is not a bug, but a carefully made heuristic. And I'm sure it was discussed many times before.

**Comment by rokejulianlockhart** [comment] 2023-06-10 18:36
https://talk.commonmark.org/t/non-spaced-indented-entirely-automatically-numbered-lists-do-not-render-and-spaced-lists-do-not-render-correct-subsequent-line-spacing/4453?u=rokejulianlockhart

**Comment by puzrin** [comment] 2023-11-18 15:23
Closing as not a bug (works as current spec says).

**Closed by puzrin** 2023-11-18 15:23 UTC
