### ISSUE TITLE
Highlight.js + markdown-it is not working

### ISSUE THREAD

**Issue by kristijorgji** [markdown-it/markdown-it#946] opened 2023-07-17 16:07 UTC
I am using React + Typescript and markdown-it + highlight.js packages.

I do not see any syntax highlight after doing code like in the Readme example.

```
    "highlight.js": "^11.8.0",
    "markdown-it": "^13.0.1",
     "@types/markdown-it": "^12.2.3",
```

Simplified code is given also below:

```
import hljs from 'highlight.js';
import MarkdownIt from 'markdown-it';

function Component() {
    const contentHtml = new MarkdownIt({
        html: true,
        highlight: function (str, lang) {
            console.log(str, lang);
            if (lang && hljs.getLanguage(lang)) {
                try {
                    return hljs.highlight(str, { language: lang }).value;
                } catch (e) {
                    console.error(e);
                    /* empty */
                }
            }

            return ''; // use external default escaping
        },
    }).render('<pre>const a = 2; console.log(a);</pre>);

    return (
        <div>
            <div dangerouslySetInnerHTML={{ __html: contentHtml }} />
        </div>
    );
}
```

The console.log inside highlight function is never called as well.

Markdownit works fine in parsing markdown + html with config above, but it just doesn't do any syntax highlight

**Comment by david-mcafee** [comment] 2023-07-21 20:51
Attempted this with a fenced code block, but highlighting is still not present.

**Comment by mbaraa** [comment] 2023-09-07 08:13
@kristijorgji of course it won't work, you're not importing a highlighting style
for example using solarized dark
```js
import "highlight.js/styles/base16/solarized-dark.css";
```

I forgot where I found it, but [here](https://github.com/mbaraa/madebybaraa/blob/main/src/lib/components/MarkdownViewer.svelte) is an example of where I used it, also if you take a look at the directory `highlight.js/styles/` you'll find a ton of other highlighting themes.

Hope I helped!

**Comment by gillo04** [comment] 2023-09-28 13:24
Could we add to the README a reference to this or to https://highlightjs.org/#usage ?

**Comment by mbaraa** [comment] 2023-09-28 15:31
sure

**Comment by puzrin** [comment] 2023-11-18 15:21
https://github.com/markdown-it/markdown-it/issues/946#issuecomment-1766004149

Closing as not a bug.

**Closed by puzrin** 2023-11-18 15:21 UTC
