### ISSUE TITLE
Emphasis cannot be recognized when it has no space with following words 

### ISSUE THREAD

**Issue by kenspirit** [markdown-it/markdown-it#285] opened 2016-09-02 07:30 UTC
Example:

For below text, the words inside \*\* cannot be converted to \<strong\> tag:
>\*\*无论\*\*这样

While if I add a space after the \*\*, it can be:
>\*\*无论\*\* 这样

**Comment by kenspirit** [comment] 2016-09-02 07:32
The finding is that if the words are english, the behavior is good.  If the words are Chinese for example, it's not working.

**Comment by kenspirit** [comment] 2016-09-02 08:13
Sorry, I found that it's not always the case.  Above sample is working, but not the below.

>**无论你是在打网球比赛，在打牌还是在选股票，有经验的人总会猜测对手会怎么做。**这样的话

**Comment by puzrin** [comment] 2016-09-08 10:10
Last example seems to be a bug.

- [Our demo (not bold)](http://markdown-it.github.io/#md3=%7B%22source%22%3A%22%2A%2A%E6%97%A0%E8%AE%BA%E4%BD%A0%E6%98%AF%E5%9C%A8%E6%89%93%E7%BD%91%E7%90%83%E6%AF%94%E8%B5%9B%EF%BC%8C%E5%9C%A8%E6%89%93%E7%89%8C%E8%BF%98%E6%98%AF%E5%9C%A8%E9%80%89%E8%82%A1%E7%A5%A8%EF%BC%8C%E6%9C%89%E7%BB%8F%E9%AA%8C%E7%9A%84%E4%BA%BA%E6%80%BB%E4%BC%9A%E7%8C%9C%E6%B5%8B%E5%AF%B9%E6%89%8B%E4%BC%9A%E6%80%8E%E4%B9%88%E5%81%9A%E3%80%82%2A%2A%E8%BF%99%E6%A0%B7%E7%9A%84%E8%AF%9D%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)
- [CM dingus (bold)](http://spec.commonmark.org/dingus/?text=**%E6%97%A0%E8%AE%BA%E4%BD%A0%E6%98%AF%E5%9C%A8%E6%89%93%E7%BD%91%E7%90%83%E6%AF%94%E8%B5%9B%EF%BC%8C%E5%9C%A8%E6%89%93%E7%89%8C%E8%BF%98%E6%98%AF%E5%9C%A8%E9%80%89%E8%82%A1%E7%A5%A8%EF%BC%8C%E6%9C%89%E7%BB%8F%E9%AA%8C%E7%9A%84%E4%BA%BA%E6%80%BB%E4%BC%9A%E7%8C%9C%E6%B5%8B%E5%AF%B9%E6%89%8B%E4%BC%9A%E6%80%8E%E4%B9%88%E5%81%9A%E3%80%82**%E8%BF%99%E6%A0%B7%E7%9A%84%E8%AF%9D)

**Comment by puzrin** [comment] 2016-09-13 06:20
[Minimal bug sample](http://markdown-it.github.io/#md3=%7B%22source%22%3A%22%2A%2A%E3%80%82%2A%2A%E8%AF%9D%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)

**Comment by rlidwka** [comment] 2016-09-13 14:00
Long story short, if you need it to be parsed as emphasis, you need to add a space character after `**` like that:

> \*\*无论你是在打网球比赛，在打牌还是在选股票，有经验的人总会猜测对手会怎么做。\*\* 这样的话

The reason is: "。" is a punctuation character (Unicode class `Po`), and one of the rules for emphasis is "if ** is placed between punctuation and an alpha, it cannot close an emphasis".

It is true for chinese text above:

> \*\*无论你是在打网球比赛，在打牌还是在选股票，有经验的人总会猜测对手会怎么做。\*\*这样的话

It is also true for an "english" text here:

> \*\*Neque dolor commodi repellat non aut nemo molestiae voluptatem.\*\*Quia ut tenetur quo quia

The fact that it's different from commonmark dingus is due to the fact that commonmark.js uses an incomplete unicode regexp (I just opened a bugreport here: https://github.com/jgm/commonmark.js/issues/108).

So I'm closing this. Not a bug, works as intended.

**Closed by rlidwka** 2016-09-13 14:00 UTC
Labels: bug

**Comment by kenspirit** [comment] 2016-09-13 15:47
@rlidwka I just wonder why that rule is set?  Grammar?  Writing style?

**Comment by puzrin** [comment] 2016-09-13 16:00
@kenspirit the best place for questions about spec is [CM forum](https://talk.commonmark.org/)

**Comment by rlidwka** [comment] 2016-09-13 16:10
@kenspirit , as far as I remember, it's a heuristic to allow nested emphasis using the same delimiter, an example would be something like this:

```md
*this is emphasis (*this is a nested emphasis*) end of emphasis*
```

The idea was to parse it like this:

```html
<em>this is emphasis (<em>this is a nested emphasis</em>) end of emphasis</em>
```

Instead of this like it would otherwise be:

```html
<em>this is emphasis (</em>this is a nested emphasis<em>) end of emphasis</em>
```

Maybe it was started here, maybe somewhere earlier than that:
https://talk.commonmark.org/t/emphasis-inside-strong-broken-in-js-implementation-when-parenthesis-involved/903

Now I see that it doesn't quite work with chinese. I don't quite understand, this language doesn't use whitespace at all?

So yeah, I'd suggest to ask about it [here](https://talk.commonmark.org/). Maybe add some examples if you think the current behavior is wrong.

**Comment by puzrin** [comment] 2016-09-13 16:13
> I'm not sure, does this language use whitespace at all?

Spaces are not used there. They also prefer translate line breaks to hard breaks by default.

**Comment by kenspirit** [comment] 2016-09-14 02:30
@rlidwka Thx for detail explanation, it's like @puzrin said, spaces are not used that often to separate between sentences.  Simply a punctuation does the work.

I am not sure how the current actual implementation logic is on parsing the tokens and translate it.  But it seems using a stack to push and pop out the \*\* to denoted a open & close of emphasis wouldn't have a problem.

**Comment by victory820** [comment] 2018-11-13 07:48
const RE = /\*\*[^*-+=.!{}]+\*\*/
const REG = /\*\*[^*-+=.!{}]+\*\*/g
function createRule (md) {
  var arrayReplaceAt = md.utils.arrayReplaceAt

  function splitTextToken (token, Token) {
    let newToken
    let lastPos = 0
    const nodes = []
    const text = token.content

    text.replace(REG, function (match, offset, src) {
      if (offset > lastPos) {
        token = new Token('text', '', 0)
        token.content = text.slice(lastPos, offset)
        nodes.push(token)
      }
      newToken = new Token('strong2', '', 0)
      newToken.content = match.replace(/\*/g, '')
      nodes.push(newToken)
      lastPos = offset + match.length
    })
    if (lastPos < text.length) {
      token = new Token('text', '', 0)
      token.content = text.slice(lastPos)
      nodes.push(token)
    }
    if (nodes.length) {
      return nodes
    } else {
      return token
    }
  }

  return function (state) {
    let i
    let j
    let l
    let tokens
    let token
    let blockTokens = state.tokens

    for (j = 0, l = blockTokens.length; j < l; j++) {
      if (blockTokens[j].type !== 'inline') { continue }
      tokens = blockTokens[j].children

      // We scan from the end, to keep position when new tags added.
      // Use reversed logic in links start/end match
      for (i = tokens.length - 1; i >= 0; i--) {
        token = tokens[i]

        if (token.type === 'text' && RE.test(token.content)) {
          blockTokens[j].children = tokens = arrayReplaceAt(
            tokens, i, splitTextToken(token, state.Token)
          )
        }
      }
    }
  }
}

export default function (md) {
  md.renderer.rules.strong2 = function (tokens, idx) {
    console.log(tokens)
    return '<strong>' + tokens[idx].content + '</strong>'
  }

  md.core.ruler.push('strong2', createRule(md))
}


custom plugin solve

**Comment by tats-u** [comment] 2023-12-18 14:12
> it's a heuristic to allow nested emphasis using the same delimiter, an example would be something like this:

[It](https://spec.commonmark.org/0.30/#left-flanking-delimiter-run) is designed under the erroneous assumption that all languages (including Chinese and Japanese!) include spaces around punctuation marks.

If the CM spec were revised taking into my suggestion, the current problem would be improved: https://github.com/commonmark/commonmark-spec/issues/650#issuecomment-1850363984

At least the Example [352](https://spec.commonmark.org/0.30/#example-352) & [379](https://spec.commonmark.org/0.30/#example-379) in the CM spec must be sacrificed for Chinese and Japanese language support.

**Comment by tats-u** [comment] 2025-01-26 15:12
Tentative solution has been released: https://www.npmjs.com/package/markdown-it-cjk-friendly
