### ISSUE TITLE
incremental compilation?

### ISSUE THREAD

**Issue by sidorares** [markdown-it/markdown-it#62] opened 2015-02-27 06:23 UTC
A lot of use case include live recompilation. Would be nice to have "incremental compilation" mode, with api like `.compileIncrementally(context, patch)`. Should not be 100% accurate - for example just handling alphanum insert in paragraphs and headers would cover most of the cases, and do a full recompile fallback otherwise

**Comment by puzrin** [comment] 2015-02-27 06:35
Honestly, i've broken my brain on shared state machine design, and don't have desire to repeat this quest again :) .

AFAIK, implementation can be done with external wrapper:

- extend range to emty strings above/below
- detect DOM elements to line mappings
- recompile range and replace

The only thing, not working well with this approach will be fenced blocks. But those can be detected by lines mapping.

Anyway, i think, this functionality is not for core.

**Comment by sidorares** [comment] 2015-02-27 06:43
agree, this can exist as external implementation and your algorithms sounds simple.
Also would be interesting to see reverce mapping: contentEditable DOM -> markdown update

**Comment by puzrin** [comment] 2015-02-27 07:03
Reverse mapping need html -> md dumper, that's completely different task.

I'd suggest to use the same approach - use the fact, that markdown blocks at top level are isolated with empty lines (that's not true for nested levels because of blockquotes). The only exclusion, fenced blocks, can be processed separately, because exact mapping is known after full pass.

Could you provide examples, when you need incremental compilation? Parser speed is 1-10mb/sec. The whole problem looks more like fast diff DOM updates, independent on parser. For example, React core tries to solve it.

**Comment by leeoniya** [comment] 2015-02-27 07:24
so not entirely what's being discussed here, but i've made some DOM > md stuff, though there's no externally accessible AST, so it basically barfs out markdown, given html. i made a bidirectional html/md editing demo using `redactor.js` and `marked`. you can take a look if interested.

repo: https://github.com/leeoniya/reMarked.js
demo: http://leeoniya.github.io/reMarked.js/
bidirectional editor: http://leeoniya.github.io/redactor-js/

the demos might not be updated to latest repo code, so if bugs happen, might be cause outdated.

**Comment by sidorares** [comment] 2015-02-27 08:11
@puzrin yes, bottleneck is probably DOM update. For example, it takes about 300ms to set html for https://markdown-it.github.io/ default text and just ~18ms to render. You could probably use the same output  to vdom + render patch to DOM approach. Would it be easy to have vdom as render target?

**Comment by puzrin** [comment] 2015-02-27 08:52
@sidorares 

> You could probably use the same output to vdom + render patch to DOM approach.

That would be useless waste of time in our case :) . We did markdown demo, not editor. With minimal efforts. Spending more time for demo will not improve parser anyhow.

> Would it be easy to have vdom as render target?

I don't know. My experience in client side programming is very basic.

**Comment by puzrin** [comment] 2015-03-04 18:37
Closing?

**Comment by sidorares** [comment] 2015-03-04 21:03
I'll message here if I have any results with vdom based rerendering

**Closed** 2015-03-04 21:03 UTC
Labels: question

**Comment by puzrin** [comment] 2015-03-04 21:12
Thanks! That would be interesting. No time to dive into it myself :( . Need to spin next markdown-it milestone (tokens/renderer refactor) & continue with nodeca.

**Comment by servermeta** [comment] 2015-04-19 16:26
I have 2 simple vdom implementations, one using blaze, one using react.js.

I'm refactoring the react.js approach, and thinking about a more generic approach which would provide a reactive div. I agree it's not easy to implement a generic solution, so it might best suited to an editor (which I'm building).

Incremental compilation could be done simply since common mark is a context free grammar (or a very good approximation of it). We should define a dictionary, and calculate the levenstein distance. 

The problem is that each plugin should extend this approach, if they don't want to break it. Again, this might be better suited for an editor.

**Comment by termvader** [comment] 2016-01-18 08:23
Hi, using [Google's Incremental DOM](https://github.com/google/incremental-dom), I've rendered markdown here: http://termvader.github.io/markdown-it-incremental-dom/

Its just a naive implementation. Not feature complete.

**Comment by puzrin** [comment] 2017-01-11 11:40
@sidorares i don't know is it actual for you or not, here is repo to design new lossless markdown AST with sourcemaps etc https://github.com/markdown-it/markdown-ast-spec.

If you wish - add your comments / issues, to make sure that new design will be convenient for missed use cases.

**Comment by purocean** [comment] 2021-11-26 01:44
I use Vue to build vdom and parse HTML correctly most of the time. I‘m still finding a way to compile Markdown incrementally. Render big Markdown content took much time when typing on editor after all.

https://github.com/purocean/yn/blob/develop/src/renderer/plugins/markdown-render-vnode.ts
https://github.com/purocean/yn/blob/develop/src/renderer/plugins/markdown-html.ts
