### ISSUE TITLE
HTML end tag issue

### ISSUE THREAD

**Issue by gautamjain14** [markdown-it/markdown-it#954] opened 2023-09-07 18:39 UTC
HTML: true / enabled

If I have a blank character in HTML end tag, then it gets rendered as is. Same is not the case with starting tag.

Assuming HTML option is true, following example:
`<Test Tag>This is a test </Test Tag>`

will be rendered as
`This is a test </Test Tag>`

I believe in open tag words after blank characters were taken as attributes.

PS: This is a custom tag that we would like to show on the UI

**Comment by gautamjain14** [comment] 2023-09-07 18:43
I believe in open tag words after space were taken as attributes.

**Comment by rlidwka** [comment] 2023-09-26 14:24
Same behaviour as with reference parser, so not a bug here:
https://spec.commonmark.org/dingus/?text=%3CTest%20Tag%3EThis%20is%20a%20test%20%3C%2FTest%20Tag%3E%0A%0A

> I believe in open tag words after space were taken as attributes.

So opening tag is valid, but closing tag is not? Since closing tags can't have attributes?

**Closed** 2023-09-26 14:26 UTC
